# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  namespace: blog
  name: blog
  labels:
    app: blog
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blog
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: europe-west1-docker.pkg.dev/bdb-container-shop-dev-6bbf/container-registry-dev/blog:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /v1/healthcheck
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: blog
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: blog-password
                  name: mysql-db-credentials
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-db-credentials
          ports:
            - containerPort: 4000
              name: blog