apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: blog
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "--"]
      args: [ "while true; do sleep 30; done;" ]